#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc config normal_border_color "#44475a"
bspc config active_border_color "#6272a4"
bspc config focused_border_color "#ff79c6"

# Establece el fondo de pantalla usando la variable $HOME para el directorio del usuario
/usr/bin/feh --bg-fill "$HOME/fondos/fondo37.jpg" &

# Iniciar otras aplicaciones
vmware-user-suid-wrapper &
"$HOME/.config/polybar/launch.sh" &
picom &
wmname LG3D &
flameshot &

# Configuración final de bspwm
#bspc config border_width 0
